"""add index to api_key_prefix

Revision ID: c9dab3c801be
Revises: cb28d15de5a8
Create Date: 2026-02-13 21:04:54.790058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9dab3c801be'
down_revision: Union[str, Sequence[str], None] = 'cb28d15de5a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client_apps', 'api_key_hash',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('client_apps', 'api_key_prefix',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=12),
               existing_nullable=False)
    op.create_index(op.f('ix_client_apps_api_key_prefix'), 'client_apps', ['api_key_prefix'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_apps_api_key_prefix'), table_name='client_apps')
    op.alter_column('client_apps', 'api_key_prefix',
               existing_type=sa.String(length=12),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    op.alter_column('client_apps', 'api_key_hash',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###
