"""add updated_at to client_apps

Revision ID: cb28d15de5a8
Revises: e6d1a2e03bb4
Create Date: 2026-02-03 17:42:25.128676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb28d15de5a8'
down_revision: Union[str, Sequence[str], None] = 'e6d1a2e03bb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "client_apps",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.alter_column("client_apps", "updated_at", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client_apps', 'api_key_hash',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('client_apps', 'updated_at')
    # ### end Alembic commands ###
