"""add api_key_prefix to client_apps

Revision ID: e6d1a2e03bb4
Revises: 682e91489d0d
Create Date: 2026-02-03 16:28:45.632273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6d1a2e03bb4'
down_revision: Union[str, Sequence[str], None] = '682e91489d0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_apps', sa.Column('api_key_prefix', sa.String(length=16), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_apps', 'api_key_prefix')
    # ### end Alembic commands ###
